---
title: "SEM"
output: html_document
date: "2026-06-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(lmerTest)
library(tidyverse)
library(lavaan)
library(hausekeep)
library(semPlot)
library(tidySEM)
```


```{r}
alt_cue <- readRDS("dominik/file_outputs/alt_cue_cleaned.RDS") 
alt_run <- readRDS("dominik/file_outputs/alt_run_cleaned.RDS")

alt_cue <- alt_cue %>%
  mutate(id = paste0("AC_", id),
         Experiment = "AC")

alt_run <- alt_run %>%
  mutate(id = paste0("AR_", id),
         Experiment = "AR")


```

# Prepping Alt Run

```{r}
set.seed(419)

alt_run <- alt_run %>%
  group_by(id, task) %>%
  mutate(N_total = n(),
         sem_group = sample(rep_len(c("A", "B", "C"), n())))

alt_cue <- alt_cue %>%
  group_by(id, task) %>%
  mutate(N_total = n(),
         sem_group = sample(rep_len(c("A", "B", "C"), n())))
 

```


# Calculating Stats

```{r}
source("dominik/functions.R")
alt_run_ddm <- alt_run %>%
  mutate(RT_s = time/1000) %>%
  group_by(id, is_bivalent_contr, prev_bivalent_contr, switch_contr, sem_group) %>%
  summarize(RT_log = mean(time_log[filter_correct == 0], na.rm = TRUE),
            RT_s_m = mean(RT_s[filter_correct == 0], na.rm = TRUE),
            RT_s_var = var(RT_s[filter_correct == 0], na.rm = TRUE),
            N_trials_total = n(),
            N_trials_forRT = sum(filter_correct == 0),
            Error = mean(error, na.rm = TRUE)) %>%
  rowwise() %>%
  mutate(ezddm = list(ezddm(propCorrect = convert_extremes(1-Error), 
                            rtCorrectVariance_seconds = RT_s_var, 
                            rtCorrectMean_seconds = RT_s_m, 
                            nTrials = N_trials))) %>%
  unnest(ezddm)


alt_cue_ddm <- alt_cue %>%
  mutate(RT_s = time/1000) %>%
  group_by(id, is_bivalent_contr, prev_bivalent_contr, switch_contr, sem_group) %>%
  summarize(RT_log = mean(time_log[filter_correct == 0], na.rm = TRUE),
            RT_s_m = mean(RT_s[filter_correct == 0], na.rm = TRUE),
            RT_s_var = var(RT_s[filter_correct == 0], na.rm = TRUE),
            N_trials_total = n(),
            N_trials_forRT = sum(filter_correct == 0),
            Error = mean(error, na.rm = TRUE)) %>%
  rowwise() %>%
  mutate(ezddm = list(ezddm(propCorrect = convert_extremes(1-Error), 
                            rtCorrectVariance_seconds = RT_s_var, 
                            rtCorrectMean_seconds = RT_s_m, 
                            nTrials = N_trials_total))) %>%
  unnest(ezddm)


```


Let's just look at correlations between groups

```{r}
alt_run_ddm_wider <- alt_run_ddm %>%
  pivot_wider(names_from = sem_group, values_from = c(v, a, Ter, RT_log, RT_s_m, RT_s_var, Error, N_trials_total, N_trials_forRT))

alt_cue_ddm_wider <- alt_cue_ddm %>%
  pivot_wider(names_from = sem_group, values_from = c(v, a, Ter, RT_log, RT_s_m, RT_s_var, Error, N_trials_total, N_trials_forRT))


cor(alt_run_ddm_wider$RT_log_A, alt_run_ddm_wider$RT_log_B, use = "pairwise.complete.obs")
cor(alt_run_ddm_wider$RT_log_A, alt_run_ddm_wider$RT_log_C, use = "pairwise.complete.obs")
cor(alt_run_ddm_wider$RT_log_B, alt_run_ddm_wider$RT_log_C, use = "pairwise.complete.obs")

cor(alt_run_ddm_wider$RT_s_m_A, alt_run_ddm_wider$RT_s_m_B, use = "pairwise.complete.obs")
cor(alt_run_ddm_wider$RT_s_m_A, alt_run_ddm_wider$RT_s_m_C, use = "pairwise.complete.obs")
cor(alt_run_ddm_wider$RT_s_m_B, alt_run_ddm_wider$RT_s_m_C, use = "pairwise.complete.obs")

cor(alt_run_ddm_wider$v_A, alt_run_ddm_wider$v_B, use = "pairwise.complete.obs")
cor(alt_run_ddm_wider$v_A, alt_run_ddm_wider$v_C, use = "pairwise.complete.obs")
cor(alt_run_ddm_wider$v_B, alt_run_ddm_wider$v_C, use = "pairwise.complete.obs")


alt_run_sem <- alt_run_ddm %>%
  mutate(dv = v) %>%
  select(id, sem_group, is_bivalent_contr, prev_bivalent_contr, switch_contr, dv) %>%
   pivot_wider(id_cols = id, names_from = c(sem_group, is_bivalent_contr, prev_bivalent_contr, switch_contr), 
              values_from = c(dv), 
              names_glue = "g{sem_group}_s{switch_contr}_lbi{prev_bivalent_contr}_cbi{is_bivalent_contr}")

colnames(alt_run_sem) <- case_when(grepl("gA_s0_lbi0_cbi0", colnames(alt_run_sem)) ~ "ARUU",
                                   grepl("gB_s0_lbi0_cbi0", colnames(alt_run_sem)) ~ "BRUU",
                                   grepl("gC_s0_lbi0_cbi0", colnames(alt_run_sem)) ~ "CRUU",
                                   grepl("gA_s0_lbi1_cbi0", colnames(alt_run_sem)) ~ "ARBU",
                                   grepl("gB_s0_lbi1_cbi0", colnames(alt_run_sem)) ~ "BRBU",
                                   grepl("gC_s0_lbi1_cbi0", colnames(alt_run_sem)) ~ "CRBU",
                                   grepl("gA_s0_lbi0_cbi1", colnames(alt_run_sem)) ~ "ARUB",
                                   grepl("gB_s0_lbi0_cbi1", colnames(alt_run_sem)) ~ "BRUB",
                                   grepl("gC_s0_lbi0_cbi1", colnames(alt_run_sem)) ~ "CRUB",
                                   grepl("gA_s0_lbi1_cbi1", colnames(alt_run_sem)) ~ "ARBB",
                                   grepl("gB_s0_lbi1_cbi1", colnames(alt_run_sem)) ~ "BRBB",
                                   grepl("gC_s0_lbi1_cbi1", colnames(alt_run_sem)) ~ "CRBB",
                                   grepl("gA_s1_lbi0_cbi0", colnames(alt_run_sem)) ~ "ASUU",
                                   grepl("gB_s1_lbi0_cbi0", colnames(alt_run_sem)) ~ "BSUU",
                                   grepl("gC_s1_lbi0_cbi0", colnames(alt_run_sem)) ~ "CSUU",
                                   grepl("gA_s1_lbi1_cbi0", colnames(alt_run_sem)) ~ "ASBU",
                                   grepl("gB_s1_lbi1_cbi0", colnames(alt_run_sem)) ~ "BSBU",
                                   grepl("gC_s1_lbi1_cbi0", colnames(alt_run_sem)) ~ "CSBU",
                                   grepl("gA_s1_lbi0_cbi1", colnames(alt_run_sem)) ~ "ASUB",
                                   grepl("gB_s1_lbi0_cbi1", colnames(alt_run_sem)) ~ "BSUB",
                                   grepl("gC_s1_lbi0_cbi1", colnames(alt_run_sem)) ~ "CSUB",
                                   grepl("gA_s1_lbi1_cbi1", colnames(alt_run_sem)) ~ "ASBB",
                                   grepl("gB_s1_lbi1_cbi1", colnames(alt_run_sem)) ~ "BSBB",
                                   grepl("gC_s1_lbi1_cbi1", colnames(alt_run_sem)) ~ "CSBB",
                                   .default = colnames(alt_run_sem))



alt_cue_sem <- alt_cue_ddm %>%
  mutate(dv = v) %>%
  select(id, sem_group, is_bivalent_contr, prev_bivalent_contr, switch_contr, dv) %>%
   pivot_wider(id_cols = id, names_from = c(sem_group, is_bivalent_contr, prev_bivalent_contr, switch_contr), 
              values_from = c(dv), 
              names_glue = "g{sem_group}_s{switch_contr}_lbi{prev_bivalent_contr}_cbi{is_bivalent_contr}")

colnames(alt_cue_sem) <- case_when(grepl("gA_s0_lbi0_cbi0", colnames(alt_cue_sem)) ~ "ARUU",
                                   grepl("gB_s0_lbi0_cbi0", colnames(alt_cue_sem)) ~ "BRUU",
                                   grepl("gC_s0_lbi0_cbi0", colnames(alt_cue_sem)) ~ "CRUU",
                                   grepl("gA_s0_lbi1_cbi0", colnames(alt_cue_sem)) ~ "ARBU",
                                   grepl("gB_s0_lbi1_cbi0", colnames(alt_cue_sem)) ~ "BRBU",
                                   grepl("gC_s0_lbi1_cbi0", colnames(alt_cue_sem)) ~ "CRBU",
                                   grepl("gA_s0_lbi0_cbi1", colnames(alt_cue_sem)) ~ "ARUB",
                                   grepl("gB_s0_lbi0_cbi1", colnames(alt_cue_sem)) ~ "BRUB",
                                   grepl("gC_s0_lbi0_cbi1", colnames(alt_cue_sem)) ~ "CRUB",
                                   grepl("gA_s0_lbi1_cbi1", colnames(alt_cue_sem)) ~ "ARBB",
                                   grepl("gB_s0_lbi1_cbi1", colnames(alt_cue_sem)) ~ "BRBB",
                                   grepl("gC_s0_lbi1_cbi1", colnames(alt_cue_sem)) ~ "CRBB",
                                   grepl("gA_s1_lbi0_cbi0", colnames(alt_cue_sem)) ~ "ASUU",
                                   grepl("gB_s1_lbi0_cbi0", colnames(alt_cue_sem)) ~ "BSUU",
                                   grepl("gC_s1_lbi0_cbi0", colnames(alt_cue_sem)) ~ "CSUU",
                                   grepl("gA_s1_lbi1_cbi0", colnames(alt_cue_sem)) ~ "ASBU",
                                   grepl("gB_s1_lbi1_cbi0", colnames(alt_cue_sem)) ~ "BSBU",
                                   grepl("gC_s1_lbi1_cbi0", colnames(alt_cue_sem)) ~ "CSBU",
                                   grepl("gA_s1_lbi0_cbi1", colnames(alt_cue_sem)) ~ "ASUB",
                                   grepl("gB_s1_lbi0_cbi1", colnames(alt_cue_sem)) ~ "BSUB",
                                   grepl("gC_s1_lbi0_cbi1", colnames(alt_cue_sem)) ~ "CSUB",
                                   grepl("gA_s1_lbi1_cbi1", colnames(alt_cue_sem)) ~ "ASBB",
                                   grepl("gB_s1_lbi1_cbi1", colnames(alt_cue_sem)) ~ "BSBB",
                                   grepl("gC_s1_lbi1_cbi1", colnames(alt_cue_sem)) ~ "CSBB",
                                   .default = colnames(alt_cue_sem))
colnames(alt_cue_sem)


cmat <- cor(alt_cue_sem %>% ungroup() %>% select(-id),
            use = "pairwise.complete.obs")

library(ggcorrplot)
ggcorrplot(cmat,
           type = "lower",
           lab  = TRUE, lab_size = 2.5,
           hc.order = F,
           colors = c("#2166AC", "white", "#B2182B")) +
  #scale_x_discrete(breaks = c("ARBB", "BRBB", "CRBB"))+
  theme(axis.text = element_text(size = 7))

all_data_sem <- bind_rows(alt_run_sem, alt_cue_sem)

```

# SEM

```{r}



full_model <- '
Spd =~ ARUU + BRUU + CRUU + 
       ARUB + BRUB + CRUB +
       ARBU + BRBU + CRBU + 
       ARBB + BRBB + CRBB +
       ASUU + BSUU + CSUU + 
       ASUB + BSUB + CSUB +
       ASBU + BSBU + CSBU + 
       ASBB + BSBB + CSBB

R =~ ARUU + BRUU + CRUU + 
     ARUB + BRUB + CRUB +
     ARBU + BRBU + CRBU + 
     ARBB + BRBB + CRBB
     
S =~ ASUU + BSUU + CSUU + 
     ASUB + BSUB + CSUB +
     ASBU + BSBU + CSBU + 
     ASBB + BSBB + CSBB

RPC =~ ARBU + BRBU + CRBU + 
       ARBB + BRBB + CRBB
RCC =~ ARUB + BRUB + CRUB + 
       ARBB + BRBB + CRBB
RPCC =~ ARBB + BRBB + CRBB


SPC =~ ASBU + BSBU + CSBU + 
       ASBB + BSBB + CSBB
SCC =~ ASUB + BSUB + CSUB + 
       ASBB + BSBB + CSBB
SPCC =~ ASBB + BSBB + CSBB

Spd ~~ 0*R + 0*S + 0*SPC + 0*SCC + 0*SPCC + 0*RPC + 0*RCC + 0*RPCC

R    ~~   S + 0*RPC + 0*RCC + 0*RPCC + 0*SPC + 0*SCC + 0*SPCC
RPC  ~~ 0*S +         0*RCC + 0*RPCC +   SPC + 0*SCC + 0*SPCC
RCC  ~~ 0*S + 0*RPC +         0*RPCC + 0*SPC +   SCC + 0*SPCC
RPCC ~~ 0*S + 0*RPC + 0*RCC +                  0*SCC +   SPCC 

S    ~~       0*SPC + 0*SCC + 0*SPCC + 0*RPC + 0*RCC + 0*RPCC
SPC  ~~ 0*R +         0*SCC + 0*SPCC +   RPC + 0*RCC + 0*RPCC
SCC  ~~ 0*R + 0*SPC +         0*SPCC + 0*RPC +   RCC + 0*RPCC
SPCC ~~ 0*R + 0*SPC + 0*SCC +          0*RPC + 0*RCC +   RPCC 

'

cfa_full_model <- cfa(full_model, data = alt_run_sem, estimator = "MLM", std.lv = TRUE)
summary(cfa_full_model, standardized=TRUE, fit.measures=TRUE, rsquare=TRUE)


semPaths(cfa_full_model, "model","standardized", 
         title = FALSE, 
         layout="tree2", 
         intercepts=FALSE, 
         bifactor="alpha", 
         rotation=2, 
         optimizeLatRes=TRUE, 
         edge.label.cex=0.83, 
         color=list(lat = rgb(229, 245, 249, maxColorValue = 255), man = rgb(153, 216, 201, maxColorValue = 255)), 
         width=11, 
         height=11)

library(semPlot)
library(tidySEM)
layout <- matrix(NA, ncol = 24, nrow = 8)
layout[1, 1] <- "R"
layout[2, 3] <- "RPC"
layout[1, 9] <- "RCC"
layout[2, 11] <- "RPCC"
layout[4, 1:12] <- c("ARUU",
                     "BRUU",
                     "CRUU",
                     "ARBU",
                     "BRBU",
                     "CRBU",
                     "BRUB",
                     "CRUB",
                     "ARUB",
                     "ARBB",
                     "BRBB",
                     "CRBB")
layout[8, 4] <- "Spd"

layout[2, 15] <- "S"
layout[3, 20] <- "SPC"
layout[4, 22] <- "SCC"
layout[5, 24] <- "SPCC"
layout[6, 11:22] <- c("ASUU",
                      "BSUU",
                      "CSUU",
                      "ASBU",
                      "BSBU",
                      "CSBU",
                      "BSUB",
                      "CSUB",
                      "ASUB",
                      "ASBB",
                      "BSBB",
                      "CSBB")


graph_data <- prepare_graph(cfa_full_model, layout = layout)
plot(graph_data)

edges(graph_data) <- edges(graph_data) %>% 
  mutate(label = est_sig_std,
         label = gsub("0\\.", ".", label),
         label = gsub("\\*", "", label),
         show = ifelse(est == "0.00", FALSE, show),
         #show = ifelse(est == "1.00", FALSE, show),
         connect_from = ifelse(from %in% c("R", "RPC", "RCC", "RPCC", "S", "SPC", "SCC", "SPCC") & to %in% colnames(alt_run_sem), "bottom", connect_from),
         connect_to   = ifelse(from %in% c("R", "RPC", "RCC", "RPCC", "S", "SPC", "SCC", "SPCC") & to %in% colnames(alt_run_sem), "top", connect_to))

plot(graph_data)
ggsave("dominik/d_figs/sem.svg", width = 60, height = 30, units = "cm")







```






