---
title: "Alternate Cues Analysis"
author:
  - name: "Dominik Graetz"
    affiliation: "University of Oregon"
  - name: "Sophia Angleton"
    affiliation: "University of Oregon"
  - name: "Neha Nagarkar"
    affiliation: "University of Oregon"
  - name: "Ulrich Mayr"
    affiliation: "University of Oregon"
output: 
  html_document:
    code_folding: hide
    toc: true         # optional: adds a table of contents
    toc_float: true
    toc_depth: 6
    number_sections: true
date: "2026-02-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

#https://osf.io/ywceb/overview
#https://osf.io/9bsf5/overview
library(tidyverse)
library(rio)
library(lmerTest)
library(hausekeep)
source("dominik/functions.R")
```


# Prep data

```{r}
#Alternate Cues
alt_cue <- import("data/AlternateCues.csv")

exclude_subjects <- alt_cue %>%
  filter(block != 0) %>%
  group_by(id) %>% 
  summarize(acc = mean(1-error),
            N = n())

exclude_subjects <- exclude_subjects %>%
  filter(acc < 0.8)

exclude_subjects <- c(exclude_subjects$id, 201, 901, 902, 959, 975)

alt_cue <- alt_cue %>%
  group_by(id, block, trial) %>%
  slice(1) %>%
  filter(!id %in% exclude_subjects) %>%
  group_by(id, block) %>%
  mutate(trialgroup = ifelse(cycle == 1, 1, 0),
         trialgroup = cumsum(trialgroup),
         is_bivalent = ifelse(dim1 == 4 | dim2 == 4, 0, 1),
         prev_bivalent = lag(is_bivalent, 1),
         was_prev_error = lag(error, 1),
         prev_task = lag(task, 1),
         switch = ifelse(prev_task == task, 0, 1)) %>%
  group_by(id, block, trialgroup) %>%
  mutate(prev_bivalent = prev_bivalent[1]) %>%
  ungroup() %>%
  mutate(id = factor(id),
         prev_bivalent = factor(prev_bivalent),
         is_bivalent = factor(is_bivalent),
         cycle = factor(cycle),
         switch = factor(switch),
         prev_bivalent_contr = case_when(prev_bivalent == 1 ~ 0.5,
                                         prev_bivalent == 0 ~ -0.5),
         is_bivalent_contr = case_when(is_bivalent == 1 ~ 0.5,
                                       is_bivalent == 0 ~ -0.5),
         switch_contr = case_when(switch == 1 ~ 1,
                                  switch == 0 ~ 0)) %>%
  filter(block != 0) %>%
  filter(trialgroup != 1) %>%
  group_by(id) %>%
  mutate(trial_cont = seq(1, n()), .after = trial) %>%
  group_by(id, prev_bivalent, is_bivalent, cycle) %>%
  mutate(time_M = mean(time[error == 0 & was_prev_error == 0]),
         time_SD = sd(time[error == 0 & was_prev_error == 0]),
         time_z = (time - time_M)/time_SD,
         time_outlier = ifelse(abs(time_z) >= 3, 1, 0),
         filter_correct = ifelse(error == 1 | was_prev_error == 1, 1, 0),
         time_log = log(time)) %>%
  filter(time_outlier == 0) 

nrow(alt_cue)
```


```{r}

model_RT_trial <- lmer(time_log ~ poly(trial_cont, 2) + (poly(trial_cont, 2)|id), 
                       control = lmerControl(optimizer = "bobyqa"),
                       alt_cue %>% 
                         filter(filter_correct == 0))


model_RT_trial %>%
  make_model_table()


alt_cue <- alt_cue %>%
  ungroup() %>%
  mutate(time_log_pred = predict(model_RT_trial, .)) #%>%
  

alt_cue$time_log_res <- NA
alt_cue$time_log_res[alt_cue$filter_correct == 0] <- residuals(model_RT_trial)

alt_cue <- alt_cue %>%
  group_by(id, block) %>%
  mutate(lag1_time_log_res = lag(time_log_res, 1))

subs <- alt_cue$id %>% unique() %>% head(5)

plt_rt_w_model <- ggplot(alt_cue %>% filter(id %in% subs), aes(x = trial_cont, y = time_log, color = block, group = interaction(id, block)))+
  geom_line(alpha = 0.5, lwd = 0.3)+
  geom_smooth(se = FALSE)+
  geom_line(aes(y = time_log_pred), color = "green")+
  scale_color_viridis_c(end = 0.8)+
  facet_grid(~id)+
  labs(x = "Continuous Trial", y = "log(RT)", title = "log(RT) with trend model, by subject")+
  theme_classic()+
  theme(legend.position = "none")

plt_rt_residuals <- ggplot(alt_cue %>% filter(id %in% subs), aes(x = trial_cont, y = time_log_res, color = block, group = interaction(id, block)))+
  geom_line(alpha = 0.5, lwd = 0.3)+
  geom_smooth(se = FALSE)+
  scale_color_viridis_c(end = 0.8)+
  facet_grid(~id)+
  labs(x = "Continuous Trial", y = "log(RT)", title = "Residual RTs, by subject")+
  theme_classic()+
  theme(legend.position = "none")

ggpubr::ggarrange(plt_rt_w_model, plt_rt_residuals, nrow = 2)



```


# Data Aggregation by cycle

```{r}
alt_cue_agg_ID <- alt_cue %>%
  group_by(id, is_bivalent, prev_bivalent, switch, cycle) %>%
  summarize(RT = mean(time[filter_correct == 0], na.rm = TRUE),
            RT_log = mean(time_log[filter_correct == 0], na.rm = TRUE),
            Error = mean(error, na.rm = TRUE))

alt_cue_agg <- alt_cue_agg_ID %>%
  normWS(s = "id", dv = "RT") %>%
  mutate(RT = DV_n) %>%
  normWS(s = "id", dv = "RT_log") %>%
  mutate(RT_log = DV_n) %>%
  normWS(s = "id", dv = "Error") %>%
  mutate(Error = DV_n) %>%
  group_by(is_bivalent, prev_bivalent, switch, cycle) %>%
  summarize(RT_m = mean(RT, na.rm = TRUE),
            RT_ci_lower = get_ci(RT, RT_m)[1],
            RT_ci_upper = get_ci(RT, RT_m)[2],
            RT_log_m = mean(RT_log, na.rm = TRUE),
            RT_log_ci_lower = get_ci(RT_log, RT_log_m)[1],
            RT_log_ci_upper = get_ci(RT_log, RT_log_m)[2],
            Error_m = mean(Error, na.rm = TRUE),
            Error_ci_lower = get_ci(Error, Error_m)[1],
            Error_ci_upper = get_ci(Error, Error_m)[2]
  )

alt_cue_contr_agg_ID <- alt_cue %>%
  group_by(id, is_bivalent, prev_bivalent, switch) %>%
  summarize(RT = mean(time[filter_correct == 0], na.rm = TRUE),
            RT_log = mean(time_log[filter_correct == 0], na.rm = TRUE),
            Error = mean(error, na.rm = TRUE))

alt_cue_contr_agg <- alt_cue_agg_ID %>%
  normWS(s = "id", dv = "RT") %>%
  mutate(RT = DV_n) %>%
  normWS(s = "id", dv = "RT_log") %>%
  mutate(RT_log = DV_n) %>%
  normWS(s = "id", dv = "Error") %>%
  mutate(Error = DV_n) %>%
  group_by(is_bivalent, prev_bivalent, switch) %>%
  summarize(RT_m = mean(RT, na.rm = TRUE),
            RT_ci_lower = get_ci(RT, RT_m)[1],
            RT_ci_upper = get_ci(RT, RT_m)[2],
            RT_log_m = mean(RT_log, na.rm = TRUE),
            RT_log_ci_lower = get_ci(RT_log, RT_log_m)[1],
            RT_log_ci_upper = get_ci(RT_log, RT_log_m)[2],
            Error_m = mean(Error, na.rm = TRUE),
            Error_ci_lower = get_ci(Error, Error_m)[1],
            Error_ci_upper = get_ci(Error, Error_m)[2]
  )


```


# Plots of correct RTs and Errors

```{r}
pos <- position_dodge(width = 0.1)

plt_rtlog_cycle <- ggplot(alt_cue_agg, aes(x = cycle, y = RT_log_m, color = is_bivalent, linetype = prev_bivalent, group = interaction(is_bivalent, prev_bivalent)))+
  geom_line(position = pos)+
  geom_errorbar(aes(ymin = RT_log_ci_lower, ymax = RT_log_ci_upper), width = 0.1, position = pos)+
  theme_classic()

plt_rt_cycle <- ggplot(alt_cue_agg, aes(x = cycle, y = RT_m, color = is_bivalent, linetype = prev_bivalent, group = interaction(is_bivalent, prev_bivalent)))+
  geom_line(position = pos)+
  geom_errorbar(aes(ymin = RT_ci_lower, ymax = RT_ci_upper), width = 0.1, position = pos)+
  theme_classic()


plt_error_cycle <- ggplot(alt_cue_agg, aes(x = cycle, y = Error_m, color = is_bivalent, linetype = prev_bivalent, group = interaction(is_bivalent, prev_bivalent)))+
  geom_line(position = pos)+
  geom_errorbar(aes(ymin = Error_ci_lower, ymax = Error_ci_upper), width = 0.1, position = pos)+
  theme_classic()

#########################

plt_rtlog_switch <- ggplot(alt_cue_contr_agg, aes(x = switch, y = RT_log_m, color = is_bivalent, linetype = prev_bivalent, group = interaction(is_bivalent, prev_bivalent)))+
  geom_line(position = pos)+
  geom_errorbar(aes(ymin = RT_log_ci_lower, ymax = RT_log_ci_upper), width = 0.1, position = pos)+
  scale_x_discrete(limits = c("1", "0"))+
  theme_classic()
plt_rtlog_switch

plt_rt_switch <- ggplot(alt_cue_contr_agg, aes(x = switch, y = RT_m, color = is_bivalent, linetype = prev_bivalent, group = interaction(is_bivalent, prev_bivalent)))+
  geom_line(position = pos)+
  geom_errorbar(aes(ymin = RT_ci_lower, ymax = RT_ci_upper), width = 0.1, position = pos)+
  scale_x_discrete(limits = c("1", "0"))+
  theme_classic()


plt_error_switch <- ggplot(alt_cue_contr_agg, aes(x = switch, y = Error_m, color = is_bivalent, linetype = prev_bivalent, group = interaction(is_bivalent, prev_bivalent)))+
  geom_line(position = pos)+
  geom_errorbar(aes(ymin = Error_ci_lower, ymax = Error_ci_upper), width = 0.1, position = pos)+
  scale_x_discrete(limits = c("1", "0"))+
  theme_classic()


ggpubr::ggarrange(plt_rtlog_cycle, plt_rtlog_switch)
ggpubr::ggarrange(plt_rt_cycle, plt_rt_switch)
ggpubr::ggarrange(plt_error_cycle, plt_error_switch)

```

# Stats: 
## RT


```{r}
alt_cue_rt_log <- lmer(time_log ~ is_bivalent_contr * prev_bivalent_contr * switch_contr + (is_bivalent_contr + prev_bivalent_contr + switch_contr||id), 
                       alt_cue %>% 
                         filter(filter_correct == 0))

make_model_table(alt_cue_rt_log)

alt_cue_rt <- lmer(time ~ is_bivalent_contr * prev_bivalent_contr * switch_contr + (is_bivalent_contr + prev_bivalent_contr + switch_contr||id), 
                   alt_cue %>% 
                     filter(filter_correct == 0))

#summary(alt_cue_rt)

make_model_table(alt_cue_rt)



```


## Errors

```{r}
alt_cue_error <- glmer(error ~ is_bivalent_contr * prev_bivalent_contr * switch_contr + (is_bivalent_contr + prev_bivalent_contr + switch_contr|id),
                       family = "binomial",
                       control = glmerControl(optimizer = "bobyqa"),
                       alt_cue)

saveRDS(alt_cue_error, "dominik/models/alt_cue_errors.RDS")
alt_cue_error <- readRDS("dominik/models/alt_cue_errors.RDS")
make_model_table(alt_cue_error)


```

# DDM analysis

## Aggregation and data processing


```{r}
alt_cue_agg_ID_ddm <- alt_cue %>%
  mutate(RT_s = time/1000) %>%
  group_by(id, is_bivalent, prev_bivalent, switch, cycle) %>%
  summarize(RT_s_m = mean(RT_s[filter_correct == 0], na.rm = TRUE),
            RT_s_var = var(RT_s[filter_correct == 0], na.rm = TRUE),
            Error = mean(error, na.rm = TRUE),
            N_trials = n()) %>%
  rowwise() %>%
  mutate(ezddm = list(ezddm(propCorrect = convert_extremes(1-Error), 
                            rtCorrectVariance_seconds = RT_s_var, 
                            rtCorrectMean_seconds = RT_s_m, 
                            nTrials = N_trials))) %>%
  unnest(ezddm)



alt_cue_agg_ddm <- alt_cue_agg_ID_ddm %>%
  group_by(id, is_bivalent, prev_bivalent, switch, cycle) %>%
  normWS(s = "id", dv = "a") %>%
  mutate(a = DV_n) %>%
  normWS(s = "id", dv = "v") %>%
  mutate(v = DV_n) %>%
  normWS(s = "id", dv = "Ter") %>%
  mutate(Ter = DV_n) %>%
  group_by(is_bivalent, prev_bivalent, switch, cycle) %>%
  summarize(a_m = mean(a, na.rm = TRUE),
            a_ci_lower = get_ci(a, a_m)[1],
            a_ci_upper = get_ci(a, a_m)[2],
            v_m = mean(v, na.rm = TRUE),
            v_ci_lower = get_ci(v, v_m)[1],
            v_ci_upper = get_ci(v, v_m)[2],
            Ter_m = mean(Ter, na.rm = TRUE),
            Ter_ci_lower = get_ci(Ter, Ter_m)[1],
            Ter_ci_upper = get_ci(Ter, Ter_m)[2],)
```

## Plots

```{r}
plt_ddm_a <- ggplot(alt_cue_agg_ddm, aes(x = cycle, y = a_m, color = is_bivalent, linetype = prev_bivalent, group = interaction(is_bivalent, prev_bivalent)))+
  geom_line(position = pos)+
  geom_errorbar(aes(ymin = a_ci_lower, ymax = a_ci_upper), width = 0.1, position = pos)+
  theme_classic()

plt_ddm_v <- ggplot(alt_cue_agg_ddm, aes(x = cycle, y = v_m, color = is_bivalent, linetype = prev_bivalent, group = interaction(is_bivalent, prev_bivalent)))+
  geom_line(position = pos)+
  geom_errorbar(aes(ymin = v_ci_lower, ymax = v_ci_upper), width = 0.1, position = pos)+
  theme_classic()


plt_ddm_Ter <- ggplot(alt_cue_agg_ddm, aes(x = cycle, y = Ter_m, color = is_bivalent, linetype = prev_bivalent, group = interaction(is_bivalent, prev_bivalent)))+
  geom_line(position = pos)+
  geom_errorbar(aes(ymin = Ter_ci_lower, ymax = Ter_ci_upper), width = 0.1, position = pos)+
  theme_classic()

ggpubr::ggarrange(plt_ddm_a, plt_ddm_v, plt_ddm_Ter, common.legend = TRUE, nrow = 1)  


```

## Statistical Models

### First prep data so that it's ignoring cycle

```{r}
alt_cue_agg_ID_ddm_nocycle <- alt_cue %>%
  mutate(RT_s = time/1000) %>%
  group_by(id, is_bivalent, is_bivalent_contr, prev_bivalent, prev_bivalent_contr, switch, switch_contr) %>%
  summarize(RT_s_m = mean(RT_s[filter_correct == 0], na.rm = TRUE),
            RT_s_var = var(RT_s[filter_correct == 0], na.rm = TRUE),
            Error = mean(error, na.rm = TRUE),
            N_trials = n()) %>%
  rowwise() %>%
  mutate(ezddm = list(ezddm(propCorrect = convert_extremes(1-Error), 
                            rtCorrectVariance_seconds = RT_s_var, 
                            rtCorrectMean_seconds = RT_s_m, 
                            nTrials = N_trials))) %>%
  unnest(ezddm)
```

### Models

```{r}
alt_cue_a <- lmer(a ~ is_bivalent_contr * prev_bivalent_contr * switch_contr + (is_bivalent_contr + switch_contr|id),
                  alt_cue_agg_ID_ddm_nocycle)

#summary(alt_cue_a)
make_model_table(alt_cue_a)

alt_cue_v <- lmer(v ~ is_bivalent_contr * prev_bivalent_contr * switch_contr + (is_bivalent_contr + switch_contr|id), 
                  alt_cue_agg_ID_ddm_nocycle)
#summary(alt_cue_v)
make_model_table(alt_cue_v)


alt_cue_Ter <- lmer(Ter ~ is_bivalent_contr * prev_bivalent_contr * switch_contr + (is_bivalent_contr + switch_contr||id), 
                    alt_cue_agg_ID_ddm_nocycle)
#summary(alt_cue_Ter)
make_model_table(alt_cue_Ter)
```



# RT residual analysis

```{r}

alt_cue_rt_log_resrt <- lmer(time_log_res ~ is_bivalent_contr * prev_bivalent_contr * switch_contr * lag1_time_log_res + (is_bivalent_contr + prev_bivalent_contr + switch_contr + lag1_time_log_res||id), control = lmerControl(optimizer = "bobyqa"),
     alt_cue %>% 
       filter(filter_correct == 0))

make_model_table(alt_cue_rt_log_resrt)

preds <- emmeans::emmeans(alt_cue_rt_log_resrt, ~ is_bivalent_contr * prev_bivalent_contr * switch_contr * lag1_time_log_res, type = "response",
                 at = list(is_bivalent_contr = c(-0.5, 0.5),
                           prev_bivalent_contr = c(-0.5, 0.5),
                           switch_contr = c(0, 1),
                           lag1_time_log_res = c(-1.5, 1.5))) %>%
  as.data.frame() %>%
  mutate(prev_bivalent = case_when(prev_bivalent_contr == -0.5 ~ 0, 
                                   prev_bivalent_contr ==  0.5 ~ 1) %>% factor(),
         is_bivalent = case_when(is_bivalent_contr == -0.5 ~ 0,
                                   is_bivalent_contr ==  0.5 ~ 1) %>% factor(),
         switch = factor(switch_contr),
         speed = case_when(lag1_time_log_res == min(lag1_time_log_res) ~ "fast",
                           lag1_time_log_res == max(lag1_time_log_res) ~ "slow") %>% factor()) 



ggplot(preds, aes(x = switch, y = emmean, color = is_bivalent, linetype = prev_bivalent, group = interaction(is_bivalent, prev_bivalent)))+
  geom_line(position = pos)+
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), position = pos)+
  scale_x_discrete(limits = c("1", "0"))+
  facet_wrap(~speed, labeller = labeller(speed = c("slow" = "lag RT slow",
                                                   "fast" = "lag RT fast")))+
  labs(title = "Model predictions for residual log RTs",
       y = "log(RT) prediction")+
  theme_classic()

```




## Lag RT based on previous trial group

```{r}


alt_cue <- alt_cue %>%
  group_by(id, block, trialgroup) %>%
  mutate(avg_ns_rt_res_log = mean(time_log_res[switch == 0], na.rm = TRUE)) %>%
  group_by(id, block) %>%
  mutate(prev_avg_ns_rt_res_log = lag(avg_ns_rt_res_log, 1)) %>%
  group_by(id, block, trialgroup) %>%
  mutate(prev_avg_ns_rt_res_log = prev_avg_ns_rt_res_log[1])
  

alt_cue_rt_log_resrt_prev <- lmer(time_log_res ~ is_bivalent_contr * prev_bivalent_contr * switch_contr * prev_avg_ns_rt_res_log + (is_bivalent_contr + prev_bivalent_contr + switch_contr + prev_avg_ns_rt_res_log||id), control = lmerControl(optimizer = "bobyqa"),
     alt_cue %>% 
       filter(filter_correct == 0))

make_model_table(alt_cue_rt_log_resrt_prev)

preds <- emmeans::emmeans(alt_cue_rt_log_resrt_prev, ~ is_bivalent_contr * prev_bivalent_contr * switch_contr * prev_avg_ns_rt_res_log, type = "response",
                 at = list(is_bivalent_contr = c(-0.5, 0.5),
                           prev_bivalent_contr = c(-0.5, 0.5),
                           switch_contr = c(0, 1),
                           prev_avg_ns_rt_res_log = c(-1.5, 1.5))) %>%
  as.data.frame() %>%
  mutate(prev_bivalent = case_when(prev_bivalent_contr == -0.5 ~ 0, 
                                   prev_bivalent_contr ==  0.5 ~ 1) %>% factor(),
         is_bivalent = case_when(is_bivalent_contr == -0.5 ~ 0,
                                   is_bivalent_contr ==  0.5 ~ 1) %>% factor(),
         switch = factor(switch_contr),
         speed = case_when(prev_avg_ns_rt_res_log == min(prev_avg_ns_rt_res_log) ~ "fast",
                           prev_avg_ns_rt_res_log == max(prev_avg_ns_rt_res_log) ~ "slow") %>% factor()) 



ggplot(preds, aes(x = switch, y = emmean, color = is_bivalent, linetype = prev_bivalent, group = interaction(is_bivalent, prev_bivalent)))+
  geom_line(position = pos)+
  geom_errorbar(aes(ymin = asymp.LCL, ymax = asymp.UCL), position = pos)+
  scale_x_discrete(limits = c("1", "0"))+
  facet_wrap(~speed, labeller = labeller(speed = c("slow" = "lag RT slow",
                                                   "fast" = "lag RT fast")))+
  labs(title = "Model predictions for residual log RTs",
       y = "log(RT) prediction")+
  theme_classic()


```

